Repository masa-finance/masa-oracle, pull requests merged in 2024-07, with the labels that each got.

#385 chore: remove core team from dependabot reviewers
  .github/dependabot.yml
Labels: ci

#391 github: add release-notes configuration
  .github/release.yml
Labels: ci

#390 fix(protocol): fail early on protocol mismatch
  pkg/network/kdht.go
Labels: bug

#404 docs: fix item lists in web scraper docs
  docs/worker-node/discord-worker.md
Labels: documentation

#409 fix: nil pointer dereference in updateRecords function
  pkg/api/handlers_node.go
  pkg/db/operations.go
  pkg/workers/workers.go
Labels: bug

#414 fix: calculation of node uptimes by looking at `recentUptime`
  pkg/pubsub/node_data.go
  pkg/pubsub/node_event_tracker.go
Labels: bug

#392 feat: ledger
  .env.example
  .github/workflows/tests.yaml
  .gitignore
  Makefile
  cmd/masa-node/main.go
  docs/oracle-node/quickstart.md
  docs/worker-node/discord-worker.md
  docs/worker-node/quickstart.md
  go.mod
  go.sum
  pkg/api/handlers_node.go
  pkg/api/routes.go
  pkg/chain/block.go
  pkg/config/welcome.go
  pkg/db/operations.go
  pkg/db/resolver_cache.go
  pkg/network/discover.go
  pkg/oracle_node.go
  pkg/pubsub/node_event_tracker.go
  pkg/pubsub/safe_map.go
  pkg/pubsub/worker_tracker.go
  pkg/tests/scraped_tweets.json
  pkg/workers/workers.go
Labels: enhancement

#438 feat: annotate the application version during build time
  Dockerfile
  Makefile
  cmd/masa-node-cli/components.go
  cmd/masa-node/main.go
  internal/constants/version.go
  pkg/config/app.go
  pkg/config/constants.go
  pkg/oracle_node.go
  pkg/pubsub/node_data.go
Labels: enhancement
