Repository masa-finance/masa-oracle, pull requests merged in 2024-08, with the labels that each got.

#472 fix: set swagger to produce relative urls for examples, autoselect http vs https
  pkg/api/handlers_node.go
  pkg/api/routes.go
  pkg/api/templates/status.html
  pkg/api/templates/swagger.html
  pkg/workers/handler.go
Labels: documentation, enhancement, prio: high

#495 chore: updates to docs
  docs/oracle-node/telegram-sentiment.md
Labels: documentation

#491 chore: Go releaser workflow
  .github/workflows/build-goreleaser-test.yml
  .github/workflows/goreleaser.yml
  .gitignore
  .goreleaser.yml
Labels: enhancement, ci
